Roave/BackwardCompatibilityCheck

.travis.yml, bin/api-compare, bin/api-compare.php, composer.json, composer.lock, src/Change.php, src/Changes.php, src/Command/ApiCompare.php, src/Comparator.php, src/Factory/DirectoryReflectorFactory.php, src/Formatter/OutputFormatter.php, src/Formatter/SymfonyConsoleTextFormatter.php, src/Git/CheckedOutRepository.php, src/Git/GitCheckoutRevisionToTemporaryPath.php, src/Git/PerformCheckoutOfRevision.php, src/Git/Revision.php, test/unit/ChangeTest.php, test/unit/ChangesTest.php, test/unit/Command/ApiCompareTest.php, test/unit/ComparatorTest.php, test/unit/Formatter/SymfonyConsoleTextFormatterTest.php, test/unit/Git/CheckedOutRepositoryTest.php, test/unit/Git/GitCheckoutRevisionToTemporaryPathTest.php, test/unit/Git/RevisionTest.php
Prototype here for running via CLI.
Usage currently like:
```
$ bin/api-compare a:c <from-rev> <to-rev>
$ bin/api-compare a:c 41231369b30957bf89881f02163b51c512c63d6f a1dffda3b9a25d7be501a3d66e50e262c98b511f
```
Note: this is a VERY rough around the edges initial implementation, and doesn't satisfy all our requirements yet (from #13). For example it doesn't do revision parsing (so it has to be full revision at the moment).
=> Run api-compare via CLI

bin/api-compare.php, src/Changes.php, src/Command/ApiCompare.php, src/Comparator.php, test/unit/Command/ApiCompareTest.php
Fixes #22 
Also makes `Comparator` non-final and injected into the command. Ideally we define an interface before we reach 1.0.0, see issue #28
=> Return 2 from CLI tool when changes are detected

LICENSE
This PR removes the *year* on the LICENSE file in order to avoid yearly updates.
=> Avoid yearly updates on LICENSE

bin/roave-backward-compatibility-check.php, src/DetectChanges/BCBreak/ClassBased/ExcludeAnonymousClasses.php, src/DetectChanges/BCBreak/FunctionBased/MultipleChecksOnAFunction.php, test/unit/DetectChanges/BCBreak/ClassBased/ExcludeAnonymousClassesTest.php
Fixes #55 
Note: the issue specifies filtering out anonymous functions too, but we don't actually reflect on functions at all at the moment; it is all just `ClassBased`, `InterfaceBased` and `TraitBased` roots; plus the top level is the `CompareClasses` implementation...
=> Filter out anonymous classes

src/CompareClasses.php, test/unit/CompareClassesTest.php
=> Skip anonymous classes in defined API

bin/roave-backward-compatibility-check.php
Closes #70 
I was trying to find a way to test this via `.travis.yml`, but the problem is that I'd need to add a composer `vcs` repository and then use a `HEAD` reference with some ugly hacks that will break everything, so I'd probably skip that for now.
@ciaranmcnulty can you please review this one? Use `?w=1` :-)
=> #70 look for further `vendor/autoload.php` locations to support in-project-dev-dependency installations

src/Command/AssertBackwardsCompatible.php, test/unit/Command/AssertBackwardsCompatibleTest.php
This addresses #72 - in my instance `hasOption` is returning true because its been replaced with its default value of `null`. 
I'm mildly surprised that this hasn't happened to anyone pre-release though - are you always specifying a revision? It's possible that this is a symfony version thing.
I stuck to the existing paradigm for the tests but there's a _lot_ of stubbing going on - it might be clearer to use a concrete ArgvInput (which would also have avoided the issue of stubbing enshrining an incorrect understanding of the API)
=> Check that from is actually provided

src/LocateDependencies/LocateDependenciesViaComposer.php, src/SourceLocator/StubClassSourceLocator.php, test/unit/LocateDependencies/LocateDependenciesViaComposerTest.php, test/unit/SourceLocator/StubClassSourceLocatorTest.php
Fixes #67 
@bendavies can I ask for a review here please, as well as checking if this allows you to integrate this tool with your project?
=> #67 stub out dependencies that cannot be located by using empty classes

.gitignore, .travis.yml, box.json.dist, build-phar.sh
The PHAR builds fine, but running it throws really weird errors. Maybe @theofidry can help? :/
```
$ dist/roave-backward-compatibility-check.phar r:a --from 1.0.0
Comparing from 81b1ab0128e72ee8e2666b28abcedadff84fcc23 to 95b5c0d5ac37ff7cfeac8368ec7f0b3009d6fd09...
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 24 installs, 0 updates, 0 removals
- Installing beberlei/assert (v2.9.5): Loading from cache
- Installing symfony/process (v4.0.11): Loading from cache
- Installing symfony/finder (v4.0.11): Loading from cache
- Installing symfony/polyfill-ctype (v1.8.0): Loading from cache
- Installing symfony/filesystem (v4.0.11): Loading from cache
- Installing symfony/polyfill-mbstring (v1.8.0): Loading from cache
- Installing …
```
=> Build PHAR using BOX and use Travis to publish PHAR releases

.travis.yml, composer.json, composer.lock
Infection 0.9 upgrades to PHP-parser 4, which means it is once again compatible.
I have left all settings the same as before. But 0.9 does create the ability to more easily disable (groups of) mutators, or even partially disable them. 0.9 also comes with new mutators, so the MSI may be lower than before.
Information
* [Release](https://github.com/infection/infection/releases/tag/0.9.0)
* [My blog post](https://backendtea.github.io/infection-09-release)
* [Official post](https://infection.github.io/2018/07/01/whats-new-in-0.9.0/)
=> Add infection back to the build

bin/roave-backward-compatibility-check.php, src/Change.php, src/DetectChanges/BCBreak/ClassBased/SkipClassBasedErrors.php, src/DetectChanges/BCBreak/ClassConstantBased/SkipClassConstantBasedErrors.php, src/DetectChanges/BCBreak/FunctionBased/SkipFunctionBasedErrors.php, src/DetectChanges/BCBreak/InterfaceBased/SkipInterfaceBasedErrors.php, src/DetectChanges/BCBreak/MethodBased/SkipMethodBasedErrors.php, src/DetectChanges/BCBreak/PropertyBased/SkipPropertyBasedErrors.php, src/DetectChanges/BCBreak/TraitBased/SkipTraitBasedErrors.php, test/unit/ChangeTest.php, test/unit/DetectChanges/BCBreak/ClassBased/ClassBecameAbstractTest.php, test/unit/DetectChanges/BCBreak/ClassBased/SkipClassBasedErrorsTest.php, test/unit/DetectChanges/BCBreak/ClassConstantBased/SkipClassConstantBasedErrorsTest.php, test/unit/DetectChanges/BCBreak/FunctionBased/SkipFunctionBasedErrorsTest.php, test/unit/DetectChanges/BCBreak/InterfaceBased/SkipInterfaceBasedErrorsTest.php, test/unit/DetectChanges/BCBreak/MethodBased/SkipMethodBasedErrorsTest.php, test/unit/DetectChanges/BCBreak/PropertyBased/SkipPropertyBasedErrorsTest.php, test/unit/DetectChanges/BCBreak/TraitBased/SkipTraitBasedErrorsTest.php
=> #85 fail-safe wrapper around BC compliance checks that access risky/throw-happy reflection API

.travis.yml, composer.json, composer.lock, phpstan.neon, src/Command/AssertBackwardsCompatible.php, src/Git/GetVersionCollectionFromGitRepository.php, src/Git/PickLastMinorVersionFromCollection.php, src/LocateDependencies/LocateDependenciesViaComposer.php, src/SourceLocator/StaticClassMapSourceLocator.php, test/unit/Command/AssertBackwardsCompatibleTest.php, test/unit/CompareClassesTest.php, test/unit/DetectChanges/BCBreak/ClassBased/ExcludeAnonymousClassesTest.php, test/unit/DetectChanges/BCBreak/ClassBased/OpenClassChangedTest.php, test/unit/DetectChanges/BCBreak/ClassConstantBased/ClassConstantValueChangedTest.php, test/unit/DetectChanges/BCBreak/ClassConstantBased/MultipleChecksOnAClassConstantTest.php, test/unit/DetectChanges/BCBreak/MethodBased/MethodBecameFinalTest.php, test/unit/DetectChanges/BCBreak/MethodBased/MethodConcretenessChangedTest.php, test/unit/DetectChanges/BCBreak/MethodBased/MethodScopeChangedTest.php, test/unit/DetectChanges/Variance/TypeIsContravariantTest.php, test/unit/DetectChanges/Variance/TypeIsCovariantTest.php, test/unit/Git/GitCheckoutRevisionToTemporaryPathTest.php, test/unit/LocateDependencies/LocateDependenciesViaComposerTest.php
Fixes #69
Provides static analysis checks also for `test/`
=> #69 re-introduced PHPStan static analysis

src/LocateDependencies/LocateDependenciesViaComposer.php, src/SourceLocator/StubClassSourceLocator.php, test/e2e/Command/AssertBackwardsCompatibleTest.php, test/unit/LocateDependencies/LocateDependenciesViaComposerTest.php
This effectively reverts #74 without introducing a BC break: the class
is now deprecated, but still exists in the codebase.
The idea of the `StubClassSourceLocator` was that it should be possible
to analyse code even if dependency holes are present, but that is now
solved by skipping BC break checks for any reflection-based exception.
This massively simplifies things, as any missing dependency will simply
lead to a skipped error and a non-zero exit code, much like it happens
in `maglnet/composer-require-checker` (https://github.com/maglnet/ComposerRequireChecker).
This also fixes weird scenarios where a pre-existing class is being
looked up in a new codebase that doesn't contain it. Assuming that
following was deleted across two breaking versions:
```php
namespace Foo;
interface Bar {} …
```
=> #98 remove `StubClassSourceLocator` from default setup

composer.json, composer.lock, src/Command/AssertBackwardsCompatible.php, src/Git/GetVersionCollection.php, src/Git/GetVersionCollectionFromGitRepository.php, src/Git/PickLastMinorVersionFromCollection.php, src/Git/PickVersionFromVersionCollection.php, test/unit/Command/AssertBackwardsCompatibleTest.php, test/unit/Git/GetVersionCollectionFromGitRepositoryTest.php, test/unit/Git/PickLastMinorVersionFromCollectionTest.php
Replaces #179
Fixes #179 
Fixes #37
=> #179 bump `nikolaposa/version` dependency to `4.0.0`

README.md
Github actions checkout has been changed, it is now only fetching the current branch without any tags. Adding a few lines extra will help to make the action work again.
=> Update github action example

composer.json, composer.lock, src/DetectChanges/BCBreak/FunctionBased/ParameterDefaultValueChanged.php
This redundant assertion led to psalm failures.
`array_intersect_key()` type inference has improved massively
in upstream, so the type is now correctly infered, without
any need for manual checking.
Fixes #206
=> Upgraded psalm, removed redundant assertion

.travis.yml, composer.json, composer.lock, infection.json.dist, src/Changes.php, src/CompareClasses.php, src/DetectChanges/BCBreak/ClassBased/MethodRemoved.php, src/DetectChanges/BCBreak/PropertyBased/PropertyDocumentedTypeChanged.php, src/Formatter/SymfonyConsoleTextFormatter.php, src/LocateDependencies/LocateDependenciesViaComposer.php, src/SourceLocator/StaticClassMapSourceLocator.php, test/unit/DetectChanges/BCBreak/ClassBased/ExcludeAnonymousClassesTest.php, test/unit/DetectChanges/BCBreak/ClassBased/ExcludeInternalClassTest.php, test/unit/DetectChanges/BCBreak/ClassBased/MultipleChecksOnAClassTest.php, test/unit/DetectChanges/BCBreak/ClassConstantBased/ClassConstantValueChangedTest.php, test/unit/DetectChanges/BCBreak/ClassConstantBased/ClassConstantVisibilityReducedTest.php, test/unit/DetectChanges/BCBreak/ClassConstantBased/MultipleChecksOnAClassConstantTest.php, test/unit/DetectChanges/BCBreak/FunctionBased/MultipleChecksOnAFunctionTest.php, test/unit/DetectChanges/BCBreak/InterfaceBased/MultipleChecksOnAnInterfaceTest.php, test/unit/DetectChanges/BCBreak/InterfaceBased/UseClassBasedChecksOnAnInterfaceTest.php, test/unit/DetectChanges/BCBreak/MethodBased/AccessibleMethodChangeTest.php, test/unit/DetectChanges/BCBreak/MethodBased/MethodFunctionDefinitionChangedTest.php, test/unit/DetectChanges/BCBreak/MethodBased/MultipleChecksOnAMethodTest.php, test/unit/DetectChanges/BCBreak/MethodBased/OnlyProtectedMethodChangedTest.php, test/unit/DetectChanges/BCBreak/MethodBased/OnlyPublicMethodChangedTest.php, test/unit/DetectChanges/BCBreak/PropertyBased/MultipleChecksOnAPropertyTest.php, test/unit/DetectChanges/BCBreak/TraitBased/MultipleChecksOnATraitTest.php, test/unit/DetectChanges/BCBreak/TraitBased/UseClassBasedChecksOnATraitTest.php, test/unit/StringReflectorFactory.php
=> Support BetterReflection 4

src/Formatter/ReflectionPropertyName.php, test/unit/DetectChanges/BCBreak/ClassBased/PropertyRemovedTest.php, test/unit/Formatter/ReflectionPropertyNameTest.php
[This PR](https://github.com/KnpLabs/php-github-api/pull/924/files#diff-8d9f29fab8b1d22b8f1b92a0be543d4b8e68ac2d475f7c3ed8da184ade8ad91f) removed a trait use from a class and the checker correctly indicated a BC break but the message was a bit confusing. So I've improved the output message for this case and added a few tests to cover this use case.
Received message:
```
[BC] REMOVED: Property Github\Api\AcceptHeaderTrait#$acceptHeaderValue was removed
```
Expected mesage:
```
[BC] REMOVED: Property Github\Api\Repository\Checks#$acceptHeaderValue was removed
```
=> Improve message for classes with removed traits with properties

src/DetectChanges/BCBreak/FunctionBased/ParameterDefaultValueChanged.php, test/unit/DetectChanges/BCBreak/FunctionBased/ParameterDefaultValueChangedTest.php
This is probably not deliberate, even if there are tests with the same issue :smile:
=> Remove extra redundant word in reported BC break text

composer.json, composer.lock
=> Support `composer/composer:^2`

test/unit/Command/AssertBackwardsCompatibleTest.php, test/unit/Formatter/SymfonyConsoleTextFormatterTest.php
`at()` is deprecated since PHPUnit 9.3
=> Replaced at() matcher with onConsecutive stub
